apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mined-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: mined.com
      http:
        paths:
          - path: /
            backend:
              serviceName: hw-svc
              servicePort: 80
    - host: www.mined.com
      http:
        paths:
          - path: /
            backend:
              serviceName: hw-svc
              servicePort: 80
