apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mined-domain-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: mined.kr
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: hw-svc
                port:
                  number: 80
    - host: www.mined.kr
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: hw-svc
                port:
                  number: 80
