apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mined-ingress
spec:
  rules:
    - host: mined.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: hw-svc
                port:
                  number: 80
    - host: www.mined.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: hw-svc
                port:
                  number: 80
