apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mined-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: mined.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: hw-svc
                port:
                  number: 8080
    - host: www.mined.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: hw-svc
                port:
                  number: 8080
