apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: mined.kr
      http:
        - pathType: Prefix
          paths: /
          backend:
            service:
              name: httpbin
              port:
                number: 80
